name: GithubAction

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew clean test

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: TestNG Results
          path: target/surefire-reports/junitreports/TEST-*.xml
          reporter: java-junit

      - name: List dependency graph files
        run: ls -l dependency-graph-reports || echo "No dependency-graph-reports directory"

      - name: Show dependency graph content (first 20 lines)
        run: head -n 20 dependency-graph-reports/githubaction-build.json || echo "No dependency graph file"

      - name: Submit dependency graph
        if: ${{ success() && steps.show-dependency-graph-content.outcome == 'success' }}
        uses: gradle/actions/dependency-submission@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          report-path: dependency-graph-reports/githubaction-build.json


